schema_version: "1.0"
mcp_name: "Taiwanese Law MCP"
jurisdiction: "TW"

sources:
  - name: "Laws & Regulations Database OpenAPI"
    authority: "Ministry of Justice, Republic of China (Taiwan)"
    official_portal: "https://law.moj.gov.tw"
    retrieval_method: "API"
    update_frequency: "weekly (Friday sync)"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "open_data"
      url: "https://law.moj.gov.tw/Service/Copyright.aspx"
      summary: "Published under Government Website Open Data License v1; reuse is permitted with attribution."
    coverage:
      scope: "Full official central legislation corpus from /api/ch/law/json and /api/ch/order/json, including article-level Chinese text and English law-name metadata where available."
      limitations: "No major known limitations for central laws and orders exposed by the OpenAPI."
    languages:
      - "zh"
      - "en"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-21"
