schema_version: "1.0"
mcp_name: "Taiwanese Law MCP"
jurisdiction: "TW"

sources:
  - name: "Laws & Regulations Database"
    authority: "Laws & Regulations Database"
    official_portal: "https://law.moj.gov.tw"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "weekly"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "Government Open Data"
      url: "https://law.moj.gov.tw"
      summary: "Official legislative texts are public domain"
    coverage:
      scope: "Data protection, cybersecurity, e-commerce, criminal law cyber provisions"
      limitations: "AI-generated seed data; full official ingestion pending"
    languages:
      - "zh"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-21"
